name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install codecov
      - name: Run tests
        run: |
          coverage run -m unittest discover
      - name: Upload coverage to Codecov
        run: |
          codecov
          [Watch the Demo Video](https://link-to-your-video)
