name: Notification
run-name: Pull Request Opened By ${{ github.actor }}

on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - develop
      - master
      - main

jobs:
  notification-job:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
    - name: Notify Contributors
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.INFINITE_LOOPERS_TOKEN}}
        script: |
          const issueNumber = context.issue.number;
          const contributors = await github.repos.listContributors({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          contributors.data.forEach(async (contributor) => {
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: `@${contributor.login} A new pull request has been created.`,
            });
          });
