# .github/workflows/build-deploy.yml
name: Notification and Deploying Project to Heroku

# on:
#   push:
#     branches:
#       - master
#       - main
#   pull_request:
#     types:
#       - opened
#       - reopened
#     branches:
#       - master
#       - dev
#       - develop

on:
  push:
    branches:
      - feature/devops
  pull_request:
    branches:
      - feature/devops

jobs:
  notification-job:
    runs-on: ubuntu-latest
    steps:
    - name: Notification
      uses: actions/github-script@v4
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const issueNumber = context.issue.number;
          await github.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issueNumber,
            body: 'Capstone!! A New Pull Request Has Been Made.',
          });

  deploy-backend:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [notification-job]
    environment:
      name: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Backend to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_BACKEND}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}

  deploy-frontend:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [notification-job]
    environment:
      name: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Frontend to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_FRONTEND}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
