name: Creating And Deploying Frontend Docker Images

on:
  push:
    branches:
      - master
      - main
      - develop
  workflow_run:
    workflows:
      - "Frontend Unit Testing"
    types:
      - completed
    branches:
      - master
      - main
      - develop

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    name: "DockerHub: Frontend"
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          echo "--------- Installing dependencies -----------"
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
          node --version # This should output the latest version from the NodeSource repository
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERUSSER }}
          password: ${{ secrets.DOCKERPASS }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push frontend Docker image
        run: |
          echo "--------- Building frontend Docker image -----------"
          docker build -t infiniteloopers-frontend-app ./frontend
          docker tag infiniteloopers-frontend-app ${{ secrets.DOCKERUSSER }}/infiniteloopers-frontend-app:v0
          docker push ${{ secrets.DOCKERUSSER }}/infiniteloopers-frontend-app:v0
        env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}