name: Creating And Deploying Frontend Docker Images

on:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:
    branches:
      - master
      - main
      - develop

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    name: "DockerHub: Frontend"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERUSSER }}
          password: ${{ secrets.DOCKERPASS }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push frontend Docker image
        run: |
          echo "--------- Building frontend Docker image -----------"
          docker build -t infiniteloopers-frontend-app ./frontend
          docker tag infiniteloopers-frontend-app ${{ secrets.DOCKERUSSER }}/infiniteloopers-frontend-app:v1
          docker push ${{ secrets.DOCKERUSSER }}/infiniteloopers-frontend-app:v1
        env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}